name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, pdo_sqlite

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets with Vite
        run: npm run build

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          echo "VITE_DISABLED=true" >> .env
          php artisan key:generate
          touch database/database.sqlite
          cat .env  # debug pour vérifier

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test
